=== LazyGeniusMan/turutan/.config/turutan/schemas/template-manifest.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "contributors": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "digest": {
      "type": "string"
    },
    "engine_version": {
      "type": "string"
    },
    "license": {
      "type": "string"
    },
    "manifestHash": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "schema_version": {
      "type": "integer"
    },
    "uri": {
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "schema_version",
    "name",
    "version",
    "author",
    "uri",
    "engine_version"
  ],
  "title": "turutan template manifest",
  "type": "object"
}

=== LazyGeniusMan/turutan/templates/default/manifest/0.2.0.json
{
  "schema_version": 1,
  "$schema": "../../../.config/turutan/schemas/template-manifest.schema.json",
  "name": "default",
  "version": "0.2.0",
  "author": "Andriyansyah Nurrachman <turutan@yansyah.my.id> (https://yansyah.my.id)",
  "uri": "oci://ghcr.io/lazygeniusman/turutan/templates/default:0.2.0",
  "digest": "sha256:32b6f64f7a96d665424b2a62bc61d4abf161dca0ce2ca1f5f7a02d0f82317f3f",
  "engine_version": "dev",
  "manifestHash": "sha256:aba5fa82b359fcd38ba3a13ca88b5c9f0ed660f9231d4d4f7bf6d247fda4f314",
  "license": "MIT-0"
}
